### ISSUE TITLE
HP 2920

### ISSUE THREAD

**Issue by jaohWork** [HPENetworking/HPEIMCUtils#21]
I am interested in using the config file for the HP 2920 
Do I need airwave for this or is a DHCP TFT combination sufficient enough.
Has anybody a working DHCP configuration ?

**Comment by netmanchris** [comment]
Not sure what you're asking for here. DHCP server configuration is going to be dependant on the type of DHCP server you're using. For the ZTP process to work, you use option 66 ( TFTP server IP address ) and option 67 ( file name ). 

Does this help?

@netmanchris

**Comment by netmanchris** [comment]
Sorry- Reread it.  No. You don't need airwave for this, or IMC for that matter. A DHCP server which points to a TFTP server that hosts the file is enough. If you want the additional functionality, such as loading the proper software version, deploying final configurations, etc.. These files have been tested specifically with IMC. They may work with Airwave, but they haven't been tested for that purpose.

@netmanchris

**Comment by netmanchris** [comment]
Closing Issue
